import { Link } from "react-router-dom";

export default function TailwindTest() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-sky-100 via-fuchsia-100 to-rose-100 px-4 py-10 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-6xl space-y-10">
        <header className="rounded-[2rem] border border-slate-200 bg-white/90 p-8 shadow-xl shadow-slate-200/40 backdrop-blur-xl">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.35em] text-fuchsia-600">Tailwind Check</p>
              <h1 className="mt-4 text-4xl font-extrabold tracking-tight text-slate-950 sm:text-5xl">
                Colorful Tailwind test page
              </h1>
              <p className="mt-4 max-w-2xl text-base leading-7 text-slate-600">
                If this page renders with gradients, rounded cards, and responsive layout, your Tailwind CSS setup is working correctly.
              </p>
            </div>
            <Link
              to="/"
              className="inline-flex items-center justify-center rounded-2xl bg-fuchsia-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-fuchsia-200/30 transition hover:bg-fuchsia-500"
            >
              Back to login
            </Link>
          </div>
        </header>

        <section className="grid gap-6 lg:grid-cols-3">
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-md shadow-slate-200/50 transition hover:-translate-y-1 hover:shadow-lg">
            <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-100 text-indigo-700">
              <span className="text-xl font-bold">A</span>
            </div>
            <h2 className="mt-6 text-xl font-semibold text-slate-950">Gradient buttons</h2>
            <p className="mt-3 text-sm leading-6 text-slate-600">Buttons with vibrant hover states prove the utility classes are compiling.</p>
            <div className="mt-6 flex flex-wrap gap-3">
              <button className="rounded-2xl bg-fuchsia-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-fuchsia-500">
                Primary
              </button>
              <button className="rounded-2xl border border-fuchsia-200 bg-white px-4 py-2 text-sm font-semibold text-fuchsia-700 transition hover:bg-fuchsia-50">
                Secondary
              </button>
            </div>
          </article>

          <article className="rounded-[2rem] border border-slate-200 bg-gradient-to-br from-emerald-100 to-sky-100 p-6 shadow-md shadow-slate-200/50">
            <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-950 text-white">
              <span className="text-xl font-bold">B</span>
            </div>
            <h2 className="mt-6 text-xl font-semibold text-slate-950">Responsive grid</h2>
            <p className="mt-3 text-sm leading-6 text-slate-700">This page uses responsive utilities and should resize cleanly on mobile devices.</p>
            <div className="mt-6 grid gap-3 sm:grid-cols-2">
              <div className="rounded-3xl bg-white p-4 text-sm text-slate-700 shadow-sm">Mobile ready</div>
              <div className="rounded-3xl bg-white p-4 text-sm text-slate-700 shadow-sm">Desktop ready</div>
            </div>
          </article>

          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-md shadow-slate-200/50">
            <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-rose-100 text-rose-700">
              <span className="text-xl font-bold">C</span>
            </div>
            <h2 className="mt-6 text-xl font-semibold text-slate-950">Utility styles</h2>
            <p className="mt-3 text-sm leading-6 text-slate-600">Text, spacing, shadows, and borders are all generated by Tailwind CSS classes.</p>
            <div className="mt-6 space-y-3 text-sm text-slate-700">
              <p className="rounded-2xl bg-slate-100 p-3">Rounded corners</p>
              <p className="rounded-2xl bg-fuchsia-50 p-3 text-fuchsia-700">Color accents</p>
              <p className="rounded-2xl bg-sky-50 p-3 text-sky-700">Soft backgrounds</p>
            </div>
          </article>
        </section>

        <section className="rounded-[2rem] border border-slate-200 bg-white/90 p-8 shadow-xl shadow-slate-200/40 backdrop-blur-xl">
          <h2 className="text-2xl font-semibold text-slate-950">Tailwind test form</h2>
          <p className="mt-3 text-sm leading-6 text-slate-600">Use the fields below to confirm Tailwind is styling inputs, text, and buttons correctly.</p>

          <div className="mt-8 grid gap-4 sm:grid-cols-2">
            <div>
              <label className="text-sm font-medium text-slate-700">Name</label>
              <input className="mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 shadow-sm focus:border-fuchsia-500 focus:outline-none focus:ring-2 focus:ring-fuchsia-100" placeholder="Jane Doe" />
            </div>
            <div>
              <label className="text-sm font-medium text-slate-700">Email</label>
              <input className="mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 shadow-sm focus:border-fuchsia-500 focus:outline-none focus:ring-2 focus:ring-fuchsia-100" placeholder="jane@example.com" />
            </div>
          </div>

          <div className="mt-6 rounded-3xl border border-slate-200 bg-fuchsia-50 p-6 text-sm text-slate-700">
            <p className="font-semibold text-fuchsia-700">Tailwind works if:</p>
            <ul className="mt-3 space-y-2 list-disc pl-5">
              <li>this list is styled</li>
              <li>the gradient background displays</li>
              <li>the buttons are colored</li>
              <li>the cards have rounded corners and shadows</li>
            </ul>
          </div>
        </section>
      </div>
    </div>
  );
}
